### ISSUE TITLE
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency

### ISSUE THREAD

**Issue by azizur** [panitw/easy-rpm#64] opened 2015-06-29 11:07 UTC
Just a heads up npm 3+ changes will affect this package.

```
npm WARN peerDependencies The peer dependency shortid@~2.0.0 included from grunt-easy-rpm will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

**Comment by paulcoyle** [comment] 2015-06-29 15:46
Can you confirm that this is occurring with the latest version (1.5.4)?  I can't reproduce this and the offending package settings were removed that would have caused this.

**Comment by azizur** [comment] 2015-07-01 19:41
I will check and get back you.

**Comment by paulcoyle** [comment] 2015-10-22 16:58
Closing; I don't believe this is an issue any longer.

**Closed by paulcoyle** 2015-10-22 16:58 UTC
